name: playground
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # supabase_flutter:
  #   path: ../supabase-flutter
  # supabase_flutter: ^1.0.0-dev.3
  # supabase: 
  #   path: ../supabase-dart
  supabase_flutter: ^1.0.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
